/**
 * Core domain types shared between API, web, and miniapp.
 */

export interface Artist {
  id: string;
  name: string;
  image?: string | null;
  bio?: string | null;
  followers?: number;
}

export interface Album {
  id: string;
  name: string;
  artistId: string;
  artistName: string;
  cover?: string | null;
  releaseDate?: string | null;
  trackCount?: number;
}

export interface Track {
  id: string;
  title: string;
  artistId: string;
  artistName: string;
  albumId?: string | null;
  albumName?: string | null;
  cover?: string | null;
  duration: number; // seconds
  audioUrl: string;
  streamUrl?: string | null;
  genre?: string | null;
  releaseDate?: string | null;
  source: 'jamendo' | 'upload' | 'fma' | 'demo';
  externalId?: string | null;
  liked?: boolean;
  /**
   * Pre-computed waveform amplitude samples in [0, 1]. ~200 buckets per
   * track. Only populated for `source: 'upload'` tracks today (generated
   * client-side at upload time via `OfflineAudioContext`). Players fall
   * back to a plain progress bar when this is `null` / missing.
   */
  peaks?: number[] | null;
  /**
   * Plain-text lyrics for upload-source tracks. Persisted on the Track row
   * (vs. fetched lazily via `LyricsService` for Jamendo / demo tracks).
   * Used as the "raw" source the Aeneas aligner consumes.
   */
  lyrics?: string | null;
  /**
   * Time-synced lyrics in standard LRC format (`[mm:ss.xx]<line>` rows).
   * Generated by the Aeneas forced-aligner sidecar. The player parses this
   * and highlights the active line as `audio.currentTime` advances. See
   * ADR-0030.
   */
  syncedLyrics?: string | null;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string | null;
  cover?: string | null;
  ownerId: string;
  ownerName?: string | null;
  isPublic: boolean;
  trackCount: number;
  tracks?: Track[];
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  email?: string | null;
  username: string;
  displayName?: string | null;
  avatar?: string | null;
  telegramId?: string | null;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface SearchResults {
  tracks: Track[];
  albums: Album[];
  artists: Artist[];
  playlists: Playlist[];
}

export type Genre =
  | 'pop'
  | 'rock'
  | 'electronic'
  | 'hiphop'
  | 'jazz'
  | 'classical'
  | 'lounge'
  | 'world'
  | 'soundtrack'
  | 'metal'
  | 'folk'
  | 'ambient';

export interface PlayerState {
  currentTrack: Track | null;
  queue: Track[];
  history: Track[];
  isPlaying: boolean;
  position: number;
  duration: number;
  volume: number;
  shuffle: boolean;
  repeat: 'off' | 'one' | 'all';
}
